### ISSUE TITLE
Duplicate IP

### ISSUE THREAD

**Issue by dnburgess** [iskandaryansergey/Prometheus-Cadvisor-Grafana#1]
This is really cool and I was able to deploy it easily, but ran into an issue with a duplicate IP on lines 130 and 131:

```
          aux_addresses:
            prometheus: 172.28.5.2
            cadvisor: 172.28.5.3
            grafana: 172.28.5.3
```

I changed the grafana line to 172.28.5.4 and everything worked fine.
